In [ ]:
# pip install cmake
# pip install dlib    (c++) visual studio 17 com (c++) visual studio build tools
# pip install face_recognition


In [ ]:
!pip install cmake
!pip install dlib
!pip install face_recognition

In [2]:

import face_recognition
import numpy as np
from PIL import Image, ImageDraw
from IPython.display import display # opencv bgr actual rgb fr rgb

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import os
os.chdir("/content/drive/MyDrive/myfiles/Face Recgonition")

In [6]:
face1 = face_recognition.load_image_file("samples/jeff_Bezos.jpg") # cv2.imread()
face2 = face_recognition.load_image_file("samples/elon_musk.jpg")

In [7]:
loc1 = face_recognition.face_locations(face1)
loc2 = face_recognition.face_locations(face2)

In [8]:
loc1

[(110, 597, 239, 468)]

In [9]:
loc2

[(295, 265, 385, 175)]

In [ ]:
encoding1 = None
encoding2 = None

In [10]:
encoding1 = face_recognition.face_encodings(face1, loc1)[0]
encoding2 = face_recognition.face_encodings(face2, loc2)[0]

In [11]:
encoding1

array([-0.04425403,  0.16284674, -0.00689598, -0.10123651, -0.05840667,
        0.06188812,  0.07570963, -0.06319906,  0.06520093, -0.09821969,
        0.24337059, -0.02556016, -0.29324359, -0.12008781,  0.05620155,
        0.16631955, -0.20140781, -0.19404252, -0.22796738, -0.10296823,
        0.07471392, -0.01648214, -0.00851484,  0.02185892, -0.17232344,
       -0.31310451, -0.07153361, -0.06441173,  0.09076793, -0.11595923,
        0.03834569, -0.03842858, -0.18351525, -0.04345103,  0.0253092 ,
        0.06737486, -0.03069888, -0.06968255,  0.15932803,  0.13625886,
       -0.17837307,  0.12541558, -0.03533857,  0.3338342 ,  0.27860957,
        0.04405968,  0.04435087, -0.10323396,  0.07309103, -0.22783592,
        0.05643079,  0.17221928,  0.13113828,  0.07467541,  0.08022088,
       -0.07778576,  0.04297259,  0.13490313, -0.2310932 , -0.02544746,
        0.04144373, -0.08963147, -0.00962687, -0.0884444 ,  0.09949902,
        0.05011346, -0.08890671, -0.16757834,  0.19565897, -0.16

In [12]:
encoding2

array([-0.02225427,  0.10928601,  0.14853166, -0.01785035, -0.10717595,
       -0.0069006 , -0.06423785, -0.18407539,  0.14231806, -0.0775783 ,
        0.23832881, -0.02833984, -0.22055747, -0.04191636, -0.02739088,
        0.10264874, -0.14708024, -0.16095217, -0.02882988, -0.08385136,
        0.08931103,  0.12310939,  0.01878818, -0.03641607, -0.13375485,
       -0.32612872, -0.12441432, -0.13102892,  0.10720674, -0.05172578,
        0.04620168,  0.04276803, -0.15886834, -0.06927705,  0.05887159,
        0.01295596, -0.0372332 , -0.06126875,  0.17902562,  0.01661422,
       -0.1727232 , -0.07572   ,  0.00854344,  0.17099003,  0.09569977,
        0.0426426 ,  0.09028977, -0.11732334,  0.04505379, -0.20399509,
        0.10384446,  0.16101262,  0.07447763,  0.0765641 ,  0.14460766,
       -0.20176594, -0.0101476 ,  0.18356931, -0.15251097,  0.15578276,
        0.07729461, -0.08637424,  0.02036329, -0.00273634,  0.15476191,
        0.02844397, -0.03946661, -0.16016091,  0.20575142, -0.07

In [13]:
res = face_recognition.compare_faces([encoding1], encoding2)

In [14]:
res

[False]

In [15]:
res = face_recognition.face_distance([encoding1], encoding2)

In [16]:
res

array([0.78493115])

In [17]:
face3 = face_recognition.load_image_file("samples/elon2.jpg")

In [18]:
loc3 = face_recognition.face_locations(face3)

In [19]:
loc3

[(142, 588, 365, 365)]

In [20]:
encoding3 = face_recognition.face_encodings(face3, loc3)[0]

In [21]:
res = face_recognition.compare_faces([encoding2], encoding3)

In [22]:
res

[True]

In [23]:
res = face_recognition.face_distance([encoding2], encoding3)

In [24]:
res

array([0.41668232])